/**
 * Daily Note Modifier - handles updating daily notes with memos
 */

import { parseMemoRecordKey } from './memoIdentity';

interface HeaderSection {
  start: number;
  end: number;
  contentStart: number;
  headerLine: string;
}

/**
 * Normalize the configured section title to a Markdown heading.
 */
function formatHeader(header: string): string {
  const trimmed = header.trim();
  return /^#+/.test(trimmed) ? trimmed : `# ${trimmed}`;
}

/**
 * Treat straight and typographic apostrophes as the same heading character.
 * This keeps old templates such as `Today‘s Memos` compatible with the new
 * default `Today's Memos`.
 */
function normalizeHeader(header: string): string {
  return formatHeader(header)
    .replace(/[\u2018\u2019\u02bc]/g, "'")
    .replace(/[ \t]+/g, ' ')
    .trim()
    .toLocaleLowerCase();
}

function findHeaderSections(content: string, targetHeader: string): HeaderSection[] {
  const headingPattern = /^(#{1,6})[ \t]+([^\r\n]+?)\r?$/gm;
  const headings = Array.from(content.matchAll(headingPattern)).map(match => ({
    start: match.index ?? 0,
    lineEnd: (match.index ?? 0) + match[0].length,
    level: match[1].length,
    headerLine: `${match[1]} ${match[2].trim()}`,
  }));
  const target = normalizeHeader(targetHeader);

  return headings
    .map((heading, index): HeaderSection | null => {
      if (normalizeHeader(heading.headerLine) !== target) return null;

      const nextHeading = headings
        .slice(index + 1)
        .find(candidate => candidate.level <= heading.level);
      const newlineLength = content.slice(heading.lineEnd, heading.lineEnd + 2) === '\r\n' ? 2 : 1;

      return {
        start: heading.start,
        end: nextHeading?.start ?? content.length,
        contentStart: Math.min(heading.lineEnd + newlineLength, content.length),
        headerLine: heading.headerLine,
      };
    })
    .filter((section): section is HeaderSection => section !== null);
}

export function extractMemoBlockIds(content: string): Set<string> {
  return new Set(Array.from(content.matchAll(/\^([A-Za-z0-9-]+)(?=\s|$)/g), match => match[1]));
}

/**
 * Memos generated by this plugin end with an alphanumeric block ID. Split a
 * section at those IDs so duplicate sections can be consolidated safely.
 */
function parseMemoRecords(content: string): Map<string, string> {
  const records = new Map<string, string>();
  const blockPattern = /\^([A-Za-z0-9-]+)(?=\s|$)/g;
  let cursor = 0;
  let match: RegExpExecArray | null;

  while ((match = blockPattern.exec(content)) !== null) {
    const end = match.index + match[0].length;
    const record = content.slice(cursor, end).trim();
    if (record && !records.has(match[1])) {
      records.set(match[1], record);
    }
    cursor = end;
  }

  return records;
}

function sortMemoContent(records: Map<string, string>, sortTimestamps = new Map<string, number>()): string {
  return Array.from(records.entries())
    .sort(([idA], [idB]) => {
      const timestampA = sortTimestamps.get(idA) ?? (/^\d+$/.test(idA) ? Number(idA) : 0);
      const timestampB = sortTimestamps.get(idB) ?? (/^\d+$/.test(idB) ? Number(idB) : 0);
      if (timestampA === 0 || timestampB === 0) return 0;
      return timestampA - timestampB;
    })
    .map(([, content]) => content.trim())
    .join('\n\n');
}

function replaceBlockId(content: string, oldId: string, newId: string): string {
  if (!oldId || oldId === newId) return content;
  const escapedOldId = oldId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return content.replace(new RegExp(`\\^${escapedOldId}(?=\\s|$)`, 'g'), `^${newId}`);
}

function contentOutsideSections(content: string, sections: HeaderSection[]): string {
  let cursor = 0;
  let result = '';
  for (const section of sections) {
    result += content.slice(cursor, section.start);
    cursor = section.end;
  }
  return result + content.slice(cursor);
}

export class DailyNoteModifier {
  private dailyMemosHeader: string;

  constructor(dailyMemosHeader: string) {
    this.dailyMemosHeader = dailyMemosHeader;
  }

  /**
   * Modify daily note content with fetched memos.
   *
   * Memos UID block IDs are the uniqueness key. Legacy numeric timestamp IDs
   * are recognized as aliases and migrated in place. A memo that already
   * exists anywhere in the Daily Note is never appended again.
   */
  modifyDailyNote(
    originFileContent: string,
    _today: string,
    fetchedRecordList: Record<string, string>,
    _isIncrementalSync = false,
    idsOutsideCurrentFile = new Set<string>(),
  ): string | undefined {
    const canonicalHeader = formatHeader(this.dailyMemosHeader);
    const sections = findHeaderSections(originFileContent, canonicalHeader);

    if (sections.length === 0) {
      const existingIds = extractMemoBlockIds(originFileContent);
      for (const id of idsOutsideCurrentFile) existingIds.add(id);
      const newRecords = new Map<string, string>();
      const sortTimestamps = new Map<string, number>();
      for (const [recordKey, remoteContent] of Object.entries(fetchedRecordList)) {
        const identity = parseMemoRecordKey(recordKey);
        if (existingIds.has(identity.blockId) || existingIds.has(identity.legacyTimestampId)) continue;
        newRecords.set(identity.blockId, remoteContent);
        sortTimestamps.set(identity.blockId, identity.timestamp);
      }
      const memoContent = sortMemoContent(newRecords, sortTimestamps);
      if (!memoContent) return undefined;

      const existingContent = originFileContent.trimEnd();
      const section = `${canonicalHeader}\n\n${memoContent}`;
      return `${existingContent}${existingContent ? '\n\n' : ''}${section}\n`;
    }

    const existingMemos = new Map<string, string>();
    for (const section of sections) {
      const sectionContent = originFileContent.slice(section.contentStart, section.end).trim();
      for (const [timestamp, record] of parseMemoRecords(sectionContent)) {
        // First occurrence wins, so already-backed-up content is never appended
        // or overwritten by a later duplicate section.
        if (!existingMemos.has(timestamp)) existingMemos.set(timestamp, record);
      }
    }

    const outsideIds = extractMemoBlockIds(contentOutsideSections(originFileContent, sections));
    for (const id of idsOutsideCurrentFile) outsideIds.add(id);
    // Backup semantics are insert-only: keep every existing unique Memo and
    // only add IDs that are not present yet. Force sync must not overwrite or
    // delete an existing backup.
    const allMemos = new Map(existingMemos);
    const sortTimestamps = new Map<string, number>();
    for (const id of allMemos.keys()) {
      if (/^\d+$/.test(id)) sortTimestamps.set(id, Number(id));
    }

    for (const [recordKey, remoteContent] of Object.entries(fetchedRecordList)) {
      const identity = parseMemoRecordKey(recordKey);
      const { blockId, legacyTimestampId, timestamp } = identity;

      // The same Memo ID elsewhere in the note is already backed up. Never add
      // another copy under the configured heading.
      if (outsideIds.has(blockId) || outsideIds.has(legacyTimestampId)) {
        allMemos.delete(blockId);
        if (legacyTimestampId !== blockId) allMemos.delete(legacyTimestampId);
        continue;
      }

      const hasUidRecord = allMemos.has(blockId);
      const hasLegacyRecord = Boolean(legacyTimestampId)
        && legacyTimestampId !== blockId
        && allMemos.has(legacyTimestampId);

      if (hasUidRecord && hasLegacyRecord) {
        const idsInFileOrder = Array.from(allMemos.keys());
        const uidFirst = idsInFileOrder.indexOf(blockId) < idsInFileOrder.indexOf(legacyTimestampId);
        const keptId = uidFirst ? blockId : legacyTimestampId;
        const keptContent = allMemos.get(keptId) as string;
        allMemos.delete(blockId);
        allMemos.delete(legacyTimestampId);
        allMemos.set(blockId, replaceBlockId(keptContent, keptId, blockId));
      } else if (hasLegacyRecord) {
        const legacyContent = allMemos.get(legacyTimestampId) as string;
        allMemos.delete(legacyTimestampId);
        allMemos.set(blockId, replaceBlockId(legacyContent, legacyTimestampId, blockId));
      } else if (!hasUidRecord) {
        allMemos.set(blockId, remoteContent);
      }
      sortTimestamps.set(blockId, timestamp);
    }

    const sortedMemos = sortMemoContent(allMemos, sortTimestamps);
    const canonicalSection = sortedMemos
      ? `${canonicalHeader}\n\n${sortedMemos}\n\n`
      : '';

    // Remove later equivalent sections from the end first so the first
    // section's offsets remain valid, then replace the first with one canonical
    // deduplicated section.
    let modified = originFileContent;
    for (let index = sections.length - 1; index >= 1; index -= 1) {
      const section = sections[index];
      modified = modified.slice(0, section.start) + modified.slice(section.end);
    }
    const first = sections[0];
    modified = modified.slice(0, first.start) + canonicalSection + modified.slice(first.end);

    return modified === originFileContent ? undefined : modified;
  }
}
